[WIP] post: LN ecosystem post sans tweets
lightninglabs/lightninglabs.github.io pull request #2
Opened 2017-06-15 02:37 UTC by MaxFangX

For some reason, after running `bundle jekyll exec serve`, the post doesn't show up in the main page of my local instance, and I can't access the post itself either, which means I can't embed tweets. Any help would be appreciated.

2017-07-04 04:39 UTC, Roasbeef requested changes

2017-07-04 04:39 UTC, Roasbeef commented on _posts/2017-06-15-lightning-network-ecosystem-overview.markdown
> +`lnd` is still in alpha, but we're already seeing a handful of developers building on top of it. In this post you can find a summary of the progress made thus far, starting first with application-lev
Lol, so are we committing to "Lapps" now? 😝

2017-07-04 04:39 UTC, Roasbeef commented on _posts/2017-06-15-lightning-network-ecosystem-overview.markdown
> +As the Bitcoin blockchain grows bigger in size, it gets more and more cost-prohibitive for individuals in the network to run full nodes, potentially leading to centralization. To directly address thi
> RiskBazaar as a "risk contract"

Did it _actually_ use risk bazaar?

2017-07-04 04:39 UTC, Roasbeef commented on _posts/2017-06-15-lightning-network-ecosystem-overview.markdown
> +Lightning recently hired me to work on developer tooling and resources - stay tuned for the full site! If you want to try building on `lnd` now, there are a few tools and guides at your disposal:
Lightning -> Lightning Labs

2017-07-04 04:45 UTC, Roasbeef commented on _posts/2017-06-15-lightning-network-ecosystem-overview.markdown
> +title:  "An Overview of the Lightning Network Ecosystem"
I'd tack on "Developer" right before "Ecosystem".

2017-07-05 04:14 UTC, MaxFangX commented on _posts/2017-06-15-lightning-network-ecosystem-overview.markdown
> +title:  "An Overview of the Lightning Network Ecosystem"
title changed as per Slack convo

2017-07-05 04:14 UTC, MaxFangX commented on _posts/2017-06-15-lightning-network-ecosystem-overview.markdown
> +Lightning recently hired me to work on developer tooling and resources - stay tuned for the full site! If you want to try building on `lnd` now, there are a few tools and guides at your disposal:
done

2017-07-05 04:21 UTC, MaxFangX commented on _posts/2017-06-15-lightning-network-ecosystem-overview.markdown
> +As the Bitcoin blockchain grows bigger in size, it gets more and more cost-prohibitive for individuals in the network to run full nodes, potentially leading to centralization. To directly address thi
I can't find their code so who knows

2017-07-05 04:22 UTC, MaxFangX commented on _posts/2017-06-15-lightning-network-ecosystem-overview.markdown
> +`lnd` is still in alpha, but we're already seeing a handful of developers building on top of it. In this post you can find a summary of the progress made thus far, starting first with application-lev
speak now or forever hold your peace

2017-07-05 16:17 UTC, Roasbeef approved these changes

2017-07-05 16:17 UTC, merged